wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.10
    cli_version: 0.16.0
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1702492115.35757
    t:
      1:
      - 5
      - 15
      - 53
      - 55
      - 105
      2:
      - 1
      - 4
      - 5
      - 6
      - 7
      - 8
      - 15
      - 53
      - 55
      - 105
      3:
      - 13
      - 23
      4: 3.9.10
      5: 0.16.0
      8:
      - 3
      - 5
      13: windows-amd64
